name: 🛠️ Build + Test

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    name: Build + Test

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version-file: ".bun-version"

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile
  
      - name: 🚀 Test + Build
        id: build
        run: |
          bun run lint
          bun test
          bun run vscode:prepublish